### ISSUE TITLE
Add feature to reduce comparisons to one-against-all

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/intertext#28]
E.g. User has a query document and a reference corpus, and doesn't care to find the all-against-all results, but just the one-against-all results

**Comment by pleonard212** [comment]
Possibility: key/value store in json metadata, something like:

`"centraltext":true"`

Only one text could have this, at least initially...

**Comment by duhaime** [comment]
This is now supported by the `--only` flag which should designate the only file for which one wishes to retain matches
