### ISSUE TITLE
Blacklist/stoplist support

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/intertext#33]
I believe the experience of ARTFL was that there was a utility in having one or more texts (the Bible, lists of commonplace expressions) declared as ignorable, to prevent uninteresting hits from cluttering up the results.  Possibly one could declare such status in the metadatajson:

`"ignorethistext":true,`

**Comment by duhaime** [comment]
This should be all set via the `--banish` (and associated `--banish_distance`) flags! 

We need to overhaul the docs to include these flags and to discuss the difference between banishment (which eliminates text/speech acts contained in the banished file(s) from all matches) and `--exclude` (which eliminates matches from excluded files from the results).

We can reopen later if we want to revisit banishment...
